package memcached

const LANGUAGES_CACHE_KEY = "languages"
const LANGUAGES_CACHE_RETENTION_SECONDS = 12 * 60 * 60
const LICENSES_CACHE_KEY = "licenses"
const LICENSES_CACHE_RETENTION_SECONDS = 12 * 60 * 60
const LABELS_CACHE_KEY = "labels"
const LABELS_CACHE_RETENTION_SECONDS = 12 * 60 * 60
