version: '3'

services:
  api:
    build:
      context: ./backend
      dockerfile: api.Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - .env
    depends_on:
      - mongodb

  job:
    build:
      context: ./backend
      dockerfile: job.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - .env
    depends_on:
      - mongodb
    tty: true

  mongodb:
    image: mongo:4.4.21
    ports:
      - 27017:27017
    volumes:
      - ./database/mongod.conf:/etc/mongod.conf
      - ./database/data:/data/db
      - ./database/configdb:/data/configdb
    env_file:
      - .env

  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    env_file:
      - .env

  nginx:
    image: nginx:1.20
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - api
