---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: "opeco17/gitnavi-api:1.9.0"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: envs
