---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config-map
data:
  mongod.conf: |
    # mongod.conf

    # for documentation of all options, see:
    #   http://docs.mongodb.org/manual/reference/configuration-options/

    # Where and how to store data.
    storage:
      dbPath: /var/lib/mongodb
      journal:
        enabled: true
    #  engine:
    #  wiredTiger:

    # where to write logging data.
    systemLog:
      destination: file
      logAppend: true
      path: /var/log/mongodb/mongod.log

    # network interfaces
    net:
      port: 27017
      bindIp: 127.0.0.1


    # how the process runs
    processManagement:
      timeZoneInfo: /usr/share/zoneinfo

    #security:

    #operationProfiling:

    #replication:

    #sharding:

    ## Enterprise-Only Options:

    #auditLog:

    #snmp:

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:4.4.21
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 27017
              name: mongo
          envFrom:
            - secretRef:
                name: envs
          volumeMounts:
            - name: mongo-config
              subPath: mongod.conf
              mountPath: /etc/mongod.conf
            - name: mongo-data
              mountPath: /data
      volumes:
        - name: mongo-config
          configMap:
            name: mongo-config-map
            items:
              - key: mongod.conf
                path: mongod.conf
        - name: mongo-data
          hostPath:
            path: /var/data/mongo
            type: DirectoryOrCreate
